### ISSUE TITLE
As a developer I want to configure the autocomplete with params defining where/how to authenticate

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_autocomplete#1]
I should be able to do something like 
```
   taxonworks_autocomplete.new({})
```

Where {} includes options

* `server` - like `sandcastle.taxonworks.org`
* `api_version` - like `v1`
* `resource` - like `taxon_names`, i.e. any of `/<resource>/autocomplete` available
* `project_token` - a project token, ultimately we need to setup API, or this widget, to try multiple tokens
* `project_id` - the id of the project authenticated against (hopefully not needed when project_token present and user not a member of project

**Comment by jlpereira** [comment]
It's already present in README.md
